# Generated by Django 4.1.3 on 2022-12-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petitions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="agree",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="petition_agree",
                to="petitions.petitionagree",
            ),
        ),
    ]
