# Generated by Django 4.1.3 on 2022-12-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("benefits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="benefit",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
