# Generated by Django 4.1.3 on 2022-12-25 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("setdurations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setdurations",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="set_durations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
